[build-system]
    build-backend="hatchling.build"
    requires=["hatchling"]

[project]
    authors=[{name="NevermindNilas"}, {name="TheRealMorgenfrue"}]
    classifiers=[
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3.13",
    ]
    dependencies=[
        # Core dependencies
        "applib",
        "setuptools==80.10.2",
        "wheel-stub==0.5.0",
        "numpy==2.2.6",
        # System and process management
        "psutil==7.2.2",
        # User interface and CLI
        "inquirer==3.4.1",
        "colored==2.3.1",
        "rich==14.3.2",         # DEPRECATED
        "rich-argparse==1.7.2", # DEPRECATED
        "tqdm>=4.67.3",
        # Video processing
        "nelux>=0.12.6",
        # CPU inference
        "opencv-python-headless==4.13.0.92",
        "timm==1.0.24",
        "onnx==1.20.0",
        "vmaf-torch==1.1.0",
        "scenedetect",
        "onnxruntime==1.24.1; sys_platform == 'linux'",
        "torchcodec==0.9.1; sys_platform == 'linux'",
        "openvino==2025.4.1; sys_platform == 'windows'",
        "onnxscript==0.6.2; sys_platform == 'windows'",
        "einops==0.8.2; sys_platform == 'windows'",
    ]
    description="A high-performance tool for video upscaling, interpolation, depth estimation, and more."
    dynamic=["version"]
    keywords=[
        "fluent-design",
        "interpolation",
        "upscaling",
        "segmentation",
        "deduplication",
    ]
    license={file="LICENSE"}
    name="TheAnimeScripter"
    readme="README.md"
    requires-python="==3.13.*"


    [project.optional-dependencies]
        # Compute platforms (Currently only NVIDIA)
        ada=[
            "torch==2.12.0",
            "torchvision>=0.24.1",
            "tensorrt>=11.0.0.114",
            "safetensors==0.7.0",
            "triton-windows==3.6.0.post25; sys_platform == 'windows'",
        ]
        ampere=[
            "torch==2.12.0",
            "torchvision>=0.24.1",
            "tensorrt>=11.0.0.114",
            "safetensors==0.7.0",
            "triton-windows==3.6.0.post25; sys_platform == 'windows'",
        ]
        blackwell=[
            "torch==2.12.0",
            "torchvision>=0.24.1",
            "tensorrt>=11.0.0.114",
            "safetensors==0.7.0",
            "triton-windows==3.6.0.post25; sys_platform == 'windows'",
        ]
        cpu=["torch==2.12.0", "torchvision>=0.24.1"]
        pascal=["torch==2.12.0", "torchvision>=0.24.1"]
        turing=[
            "torch==2.12.0",
            "torchvision>=0.24.1",
            "tensorrt>=11.0.0.114",
            "safetensors==0.7.0",
            "triton-windows==3.6.0.post25; sys_platform == 'windows'",
        ]

    [project.urls]
        Documentation="https://example.com"
        Homepage="https://github.com/TheRealMorgenfrue/TheAnimeScripter"

[dependency-groups]
    dev=[{include-group="lint"}]
    lint=["ruff"]


[tool.uv]
    conflicts=[
        [
            {extra="cpu"},
            {extra="pascal"},
            {extra="turing"},
            {extra="ampere"},
            {extra="ada"},
            {extra="blackwell"},
        ],
    ]

    [tool.uv.sources]
        tensorrt={index="nvidia"}
        torch=[
            {index="cpu", extra="cpu"},
            {index="cu126", extra="pascal"},
            {index="cu130", extra="turing"},
            {index="cu130", extra="ampere"},
            {index="cu130", extra="ada"},
            {index="cu130", extra="blackwell"},
        ]
        torchvision=[
            {index="cu126", extra="cpu"},
            {index="cu126", extra="pascal"},
            {index="cu130", extra="turing"},
            {index="cu130", extra="ampere"},
            {index="cu130", extra="ada"},
            {index="cu130", extra="blackwell"},
        ]

        # applib={git="https://github.com/TheRealMorgenfrue/AppLib"}
        applib={path="../AppLib", editable=true}

    [[tool.uv.index]]
        explicit=true
        name="cpu"
        url="https://download.pytorch.org/whl/cpu"

    [[tool.uv.index]]
        explicit=true
        name="cu126"
        url="https://download.pytorch.org/whl/cu126"

    [[tool.uv.index]]
        explicit=true
        name="cu130"
        url="https://download.pytorch.org/whl/cu130"

    [[tool.uv.index]]
        explicit=true
        name="nvidia"
        url="https://pypi.nvidia.com"

[tool.hatch]
    [tool.hatch.version]
        path="src/version.py"

    [tool.hatch.build.targets.wheel]
        packages=["src"]

[tool.ruff]
    [tool.ruff.format]
        docstring-code-format=true

    [tool.ruff.lint]
        fixable=["ALL"]
        ignore=[
            "E501", # Avoid enforcing line-length violations
            "E402", # Module level import not at top of file
        ]
        select=[
            'F', # Pyflakes
            'E', # pycodestyle (Error)
            'I', # isort
            #'D',      # pydocstyle
            'UP',     # pyupgrade
            'YTT',    # flake8-2020
            'B',      # flake8-bugbear
            'T10',    # flake8-debugger
            'T20',    # flake8-print
            'C4',     # flake8-comprehensions
            'PERF',   # Perflint
            'PIE',    # flake8-pie
            'PYI006', # flake8-pyi
            'PYI062', # flake8-pyi
            'PYI063', # flake8-pyi
            'PYI066', # flake8-pyi
        ]
