[build-system]
    build-backend="hatchling.build"
    requires=["hatchling"]

[project]
    authors=[{name="NevermindNilas"}, {name="TheRealMorgenfrue"}]
    classifiers=[
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3.13",
    ]
    dependencies=[
        # Core dependencies
        "numpy>=2.2.6",
        # System and process management
        "psutil==7.2.2",
        # User interface and CLI
        "applib",
        "tqdm>=4.67.3",
        # Video processing
        "nelux>=0.12.6",
        "opencv-python-headless==4.13.0.92",
        # Inference
        "onnxruntime==1.26.0",
        "onnx==1.22.0",
        "transformers",
    ]
    description="A high-performance tool for video upscaling, interpolation, depth estimation, and more."
    dynamic=["version"]
    keywords=[
        "fluent-design",
        "interpolation",
        "upscaling",
        "segmentation",
        "deduplication",
    ]
    license={file="LICENSE"}
    name="TheAnimeScripter-Redux"
    readme="README.md"
    requires-python=">=3.13"


    [project.optional-dependencies]
        # Compute platforms (NVIDIA, AMD, Intel, Apple)
        ada=[
            "torch==2.12.0",
            "torchvision",
            "onnxruntime-gpu==1.26.0",
            "tensorrt>=11.0.0.114",
            "olive-ai[gpu]>=0.13.0",
        ]
        # AMD repo has dependency resolution issues
        # amd=[
        #     "torch==2.12.0",
        #     "torchvision",
        #     # "torch_migraphx==1.1; sys_platform == 'linux'", # numpy compatibility issue (only 1.20 supported)
        #     "olive-ai[cpu]>=0.13.0",
        # ]
        ampere=[
            "torch==2.12.0",
            "torchvision",
            "onnxruntime-gpu==1.26.0",
            "tensorrt>=11.0.0.114",
            "olive-ai[gpu]>=0.13.0",
        ]
        apple=["torch==2.12.0", "torchvision", "olive-ai[cpu]>=0.13.0"]
        blackwell=[
            "torch==2.12.0",
            "torchvision",
            "onnxruntime-gpu==1.26.0",
            "tensorrt>=11.0.0.114",
            "olive-ai[gpu]>=0.13.0",
        ]
        cpu=["torch==2.12.0", "torchvision", "olive-ai[cpu]>=0.13.0"]
        intel=[
            "torch==2.12.0",
            "torchvision",
            "openvino==2025.4.1",
            "onnxruntime-openvino==1.24.1",
            "olive-ai[cpu]>=0.13.0",
        ]
        pascal=[
            "torch==2.12.0",
            "torchvision",
            "onnxruntime-gpu==1.26.0",
            "olive-ai[gpu]>=0.13.0",
        ]
        turing=[
            "torch==2.12.0",
            "torchvision",
            "onnxruntime-gpu==1.26.0",
            "tensorrt>=11.0.0.114",
            "olive-ai[gpu]>=0.13.0",
        ]

    [project.urls]
        Documentation="https://example.com"
        Homepage="https://github.com/TheRealMorgenfrue/TheAnimeScripter"

[dependency-groups]
    dev=[{include-group="lint"}]
    lint=["ruff"]


[tool.uv]
    conflicts=[
        [
            {extra="cpu"},
            # {extra="amd"},
            {extra="intel"},
            {extra="apple"},
            {extra="pascal"},
            {extra="turing"},
            {extra="ampere"},
            {extra="ada"},
            {extra="blackwell"},
        ],
    ]

    [tool.uv.sources]
        # olive-ai={git="https://github.com/TheRealMorgenfrue/Olive"}
        olive-ai={path="../Others_Code/Olive"}
        tensorrt={index="nvidia"}
        torch=[
            {index="cpu", extra="cpu"},
            # {index="rocm", extra="amd"},
            {index="cpu", extra="intel"},
            {index="cpu", extra="apple"},
            {index="cu126", extra="pascal"},
            {index="cu130", extra="turing"},
            {index="cu130", extra="ampere"},
            {index="cu130", extra="ada"},
            {index="cu130", extra="blackwell"},
        ]
        torchvision=[
            {index="cpu", extra="cpu"},
            # {index="rocm", extra="amd"},
            {index="cpu", extra="intel"},
            {index="cpu", extra="apple"},
            {index="cu126", extra="pascal"},
            {index="cu130", extra="turing"},
            {index="cu130", extra="ampere"},
            {index="cu130", extra="ada"},
            {index="cu130", extra="blackwell"},
        ]
        # applib={git="https://github.com/TheRealMorgenfrue/AppLib"}
        applib={path="../AppLib", editable=true}

    [[tool.uv.index]]
        explicit=true
        name="cpu"
        url="https://download.pytorch.org/whl/cpu"

        # [[tool.uv.index]]
        #     explicit=true
        #     name="rocm"
        #     url="https://download.pytorch.org/whl/rocm7.2"

    [[tool.uv.index]]
        explicit=true
        name="cu126"
        url="https://download.pytorch.org/whl/cu126"

    [[tool.uv.index]]
        explicit=true
        name="cu130"
        url="https://download.pytorch.org/whl/cu130"

    [[tool.uv.index]]
        explicit=true
        name="nvidia"
        url="https://pypi.nvidia.com"

[tool.hatch]
    [tool.hatch.version]
        path="src/version.py"

    [tool.hatch.build.targets.wheel]
        packages=["src"]

[tool.ruff]
    [tool.ruff.format]
        docstring-code-format=true

    [tool.ruff.lint]
        fixable=["ALL"]
        ignore=[
            "E501", # Avoid enforcing line-length violations
        ]
        select=[
            'F', # Pyflakes
            'E', # pycodestyle (Error)
            'I', # isort
            #'D',      # pydocstyle
            'UP',     # pyupgrade
            'YTT',    # flake8-2020
            'B',      # flake8-bugbear
            'T10',    # flake8-debugger
            'T20',    # flake8-print
            'C4',     # flake8-comprehensions
            'PERF',   # Perflint
            'PIE',    # flake8-pie
            'PYI006', # flake8-pyi
            'PYI062', # flake8-pyi
            'PYI063', # flake8-pyi
            'PYI066', # flake8-pyi
        ]
