from applib import (
    AutoTextWrap,
    ComboBoxOption,
    CompatilityValidator,
    GUIMessage,
    Option,
    UIGroups,
)

from src.module.config.runners.compatibility.depth_compatibility import (
    compatible_depth_model,
)


def tas_depth_estimation_template() -> dict:
    return {
        "depth": Option(
            default=False,
            ui_group="g_depth",
            ui_group_parent=[UIGroups.NESTED_CHILDREN],
            ui_info=GUIMessage("Estimate the depth of the video"),
        ),
        "depth_method": ComboBoxOption(
            default="small_v2",
            values=[
                "small_v2",
                "base_v2",
                "large_v2",
                "giant_v2",
                "distill_small_v2",
                "distill_base_v2",
                "distill_large_v2",
                "og_small_v2",
                "og_base_v2",
                "og_large_v2",
                "og_giant_v2",
                "og_distill_small_v2",
                "og_distill_base_v2",
                "og_distill_large_v2",
                "og_video_small_v2",
                "og_video_base_v2",
                "og_video_large_v2",
                "video_small_v2",
                "video_large_v2",
                "small_v2-tensorrt",
                "base_v2-tensorrt",
                "large_v2-tensorrt",
                "distill_small_v2-tensorrt",
                "distill_base_v2-tensorrt",
                "distill_large_v2-tensorrt",
                "small_v2-directml",
                "base_v2-directml",
                "large_v2-directml",
                "distill_small_v2-directml",
                "distill_base_v2-directml",
                "distill_large_v2-directml",
                "og_small_v2-tensorrt",
                "og_base_v2-tensorrt",
                "og_large_v2-tensorrt",
                "og_distill_small_v2-tensorrt",
                "og_distill_base_v2-tensorrt",
                "og_distill_large_v2-tensorrt",
                "small_v3",
                "base_v3",
                "large_v3",
                "giant_v3",
                "small_v3-directml",
                "base_v3-directml",
                "large_v3-directml",
                "giant_v3-directml",
                "small_v3-tensorrt",
                "base_v3-tensorrt",
                "large_v3-tensorrt",
                "giant_v3-tensorrt",
                "small_v2-openvino",
                "base_v2-openvino",
                "large_v2-openvino",
                "distill_small_v2-openvino",
                "distill_base_v2-openvino",
                "distill_large_v2-openvino",
                "og_small_v2-openvino",
                "og_base_v2-openvino",
                "og_large_v2-openvino",
                "small_v3-openvino",
                "base_v3-openvino",
                "large_v3-openvino",
                "giant_v3-openvino",
            ],
            ui_group="g_depth",
            ui_info=GUIMessage(
                "Depth estimation method",
            ),
        ),
        "depth_quality": ComboBoxOption(
            default="low",
            values=["low", "medium", "high"],
            ui_info=GUIMessage(
                "This will determine the quality of the depth map",
                AutoTextWrap().text_format(
                    "Low is significantly faster, but lower quality."
                    "Only works with CUDA depth maps"
                ),
            ),
            validators=CompatilityValidator(compatible_depth_model, ["depth_method"]),
        ),
    }
