from applib import (
    ComboBoxOption,
    FileSelectorOption,
    GUIMessage,
    Option,
    UIGroups,
    validate_path,
)


def tas_sr_template() -> dict:
    return {
        "sr": Option(
            default=False,
            ui_group="g_sr",
            ui_group_parent=[UIGroups.NESTED_CHILDREN],
            ui_info=GUIMessage("Upscale the video"),
        ),
        "sr_factor": ComboBoxOption(
            default=2,
            values=[2, 3, 4],
            ui_group="g_sr",
            ui_info=GUIMessage("Upscaling factor"),
        ),
        "sr_model": ComboBoxOption(
            default="shufflecugan",
            values=[
                "shufflecugan",
                "fallin_soft",
                "fallin_soft-tensorrt",
                "fallin_soft-directml",
                "fallin_strong",
                "fallin_strong-tensorrt",
                "fallin_strong-directml",
                "compact",
                "ultracompact",
                "superultracompact",
                "span",
                "compact-directml",
                "ultracompact-directml",
                "superultracompact-directml",
                "shufflespan-directml",
                "span-directml",
                "shufflecugan-ncnn",
                "shufflecugan-directml",
                "shufflecugan-openvino",
                "span-ncnn",
                "compact-tensorrt",
                "ultracompact-tensorrt",
                "superultracompact-tensorrt",
                "span-tensorrt",
                "shufflecugan-tensorrt",
                "shufflespan-tensorrt",
                "open-proteus",
                "open-proteus-tensorrt",
                "open-proteus-directml",
                "aniscale2",
                "aniscale2-tensorrt",
                "aniscale2-directml",
                "rtmosr",
                "rtmosr-tensorrt",
                "rtmosr-directml",
                "saryn",
                "saryn-tensorrt",
                "saryn-directml",
                "animesr",
                "animesr-tensorrt",
                "animesr-directml",
                "animesr-openvino",
                "compact-openvino",
                "ultracompact-openvino",
                "superultracompact-openvino",
                "span-openvino",
                "open-proteus-openvino",
                "aniscale2-openvino",
                "shufflespan-openvino",
                "rtmosr-openvino",
                "saryn-openvino",
                "fallin_soft-openvino",
                "fallin_strong-openvino",
                "gauss",
                "gauss-tensorrt",
                "gauss-directml",
                "gauss-openvino",
            ],
            ui_group="g_sr",
            ui_info=GUIMessage("Upscaling method"),
        ),
        "custom_model": FileSelectorOption(
            default="",
            ui_file_filter=None,
            ui_group="g_sr",
            ui_info=GUIMessage("Path to custom upscaling model"),
            validators=validate_path,
        ),
    }
