from applib import ComboBoxOption, GUIMessage, NumberOption, Option, UIGroups


def tas_vfi_template() -> dict:
    return {
        "vfi": Option(
            default=False,
            ui_group="g_vfi",
            ui_group_parent=[UIGroups.NESTED_CHILDREN],
            ui_info=GUIMessage("Interpolate the video"),
        ),
        "vfi_factor": NumberOption(
            default=2.0,
            min=0,
            max=None,
            ui_group="g_vfi",
            ui_info=GUIMessage("Interpolation factor"),
        ),
        "vfi_model": ComboBoxOption(
            default="rife4.6",
            values=[
                "distildrba",
                "distildrba-lite",
                "distildrba-tensorrt",
                "distildrba-lite-tensorrt",
                "atr",
                "rife4.6",
                "rife4.15-lite",
                "rife4.16-lite",
                "rife4.17",
                "rife4.18",
                "rife4.20",
                "rife4.21",
                "rife4.22",
                "rife4.22-lite",
                "rife4.25",
                "rife4.25-depth",
                "rife4.25-lite",
                "rife4.25-heavy",
                "rife-ncnn",
                "rife4.6-ncnn",
                "rife4.15-lite-ncnn",
                "rife4.16-lite-ncnn",
                "rife4.17-ncnn",
                "rife4.18-ncnn",
                "rife4.20-ncnn",
                "rife4.21-ncnn",
                "rife4.22-ncnn",
                "rife4.22-lite-ncnn",
                "rife4.6-tensorrt",
                "rife4.15-tensorrt",
                "rife4.17-tensorrt",
                "rife4.18-tensorrt",
                "rife4.20-tensorrt",
                "rife4.21-tensorrt",
                "rife4.22-tensorrt",
                "rife4.22-lite-tensorrt",
                "rife4.25-tensorrt",
                "rife4.25-lite-tensorrt",
                "rife4.25-heavy-tensorrt",
                "rife-tensorrt",
                "gmfss",
                "gmfss-tensorrt",
                "rife_elexor",
                "rife_elexor-tensorrt",
                "rife4.6-tensorrt",
                "rife4.6-directml",
                "rife4.15-directml",
                "rife4.17-directml",
                "rife4.18-directml",
                "rife4.20-directml",
                "rife4.21-directml",
                "rife4.22-directml",
                "rife4.22-lite-directml",
                "rife4.25-directml",
                "rife4.25-lite-directml",
                "rife4.25-heavy-directml",
                "rife4.6-openvino",
                "rife4.15-openvino",
                "rife4.17-openvino",
                "rife4.18-openvino",
                "rife4.20-openvino",
                "rife4.21-openvino",
                "rife4.22-openvino",
                "rife4.22-lite-openvino",
                "rife4.25-openvino",
                "rife4.25-lite-openvino",
                "rife4.25-heavy-openvino",
            ],
            ui_group="g_vfi",
            ui_info=GUIMessage("Interpolation method"),
        ),
        "slowmo": Option(
            default=False,
            ui_group="g_vfi",
            ui_info=GUIMessage(
                "Enable slow motion interpolation, this will slow down the video instead of increasing the frame rate"
            ),
        ),
        "ensemble": Option(
            default=False,
            ui_group="g_vfi",
            ui_info=GUIMessage("Use the ensemble model for interpolation"),
        ),
        "dynamic_scale": Option(
            default=False,
            ui_group="g_vfi",
            ui_info=GUIMessage(
                "Use dynamic scaling for interpolation, this can improve the quality of the interpolation at the cost of performance",
                "This is experimental and only works with Rife CUDA",
            ),
        ),
        "static_step": Option(
            default=False,
            ui_group="g_vfi",
            ui_info=GUIMessage("Force static timestep generation for Rife CUDA"),
        ),
        "vfi_first": Option(
            default=False,
            ui_group="g_vfi",
            ui_info=GUIMessage(
                "Switch back to the old approach where interpolated frames would instantly be written to the write queue"
            ),
        ),
    }
